=== CJSCommonPlatform/json-resources-spike/domain/src/main/resources/json/schema/stagingtfl.events.charged-cases-csv-files-upload-accepted.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "uploadId": {
      "$ref": "#/definitions/uuid"
    },
    "headerFileReference": {
      "$ref": "#/definitions/uuid"
    },
    "headerFilename": {
      "type": "string"
    },
    "offenceFileReference": {
      "$ref": "#/definitions/uuid"
    },
    "offenceFilename": {
      "type": "string"
    },
    "timestamp": {
      "type": "string",
      "format": "date-time"
    }
  },
  "required": [
    "uploadId",
    "headerFileReference",
    "headerFilename",
    "offenceFileReference",
    "offenceFilename",
    "timestamp"
  ],
  "definitions": {
    "uuid": {
      "type": "string",
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
    }
  }
}

=== CJSCommonPlatform/json-resources-spike/domain/src/main/resources/json/stagingtfl.events.charged-cases-csv-files-upload-accepted.json
{
  "uploadId": "b2569c8a-2deb-3578-82a3-2d2b6cd79fcb",
  "headerFileReference": "a9569c8a-2deb-4578-82a3-2d2b6cd79fee",
  "headerFilename": "header.csv",
  "offenceFileReference": "e4569c8d-2deb-4578-82a3-2d2b6cd59fe3",
  "offenceFilename": "offence.csv",
  "timestamp": "2016-12-16T13:47:01.115Z"
}
